[package]
name = "test_fixed_division"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bnum = { version = "0.9.0", features = ["nightly"] }
num = "0.4.1"
